[build]
  publish = "dist"
  command = "mkdir -p dist && cp *.html dist/ && cp -r public dist/ && cp main.js dist/ && cp _redirects dist/"

[[redirects]]
  from = "/features"
  to = "/features.html"
  status = 200

[[redirects]]
  from = "/features/"
  to = "/features.html"
  status = 200